### ISSUE TITLE
difference between ClientOnlyResourceOwnerPasswordResourceDetails and ResourceOwnerPasswordResourceDetails?

### ISSUE THREAD

**Issue by sridhar1982** [mariubog/oauth-client-sample#2]
@mariubog A very good material for spinning up services that talk to Authorization server.  :+1:

I have a few questions as I browsed through your code?

1. what is the difference between `ClientOnlyResourceOwnerPasswordResourceDetails` and  `ResourceOwnerPasswordResourceDetails` that you have used in `OauthClientConfig.java`? 
when should I use one over the other?

2. Similarly in `MyRestController.java`, you have used `oauthConnectionService.getClientOnlyResults` and `oauthConnectionService.getResults`? what is the difference here and when to prefer one over the other?

3.  In the `OauthClientConfig.java`, you have hard-coded the values for username and password. If I want to this use this client to accept username and password (either as HTTP basic header) or request param and set them on resource (below code) before making OAuth request, how can this be done?

something like this
`http://localhost:8005/results-asynch?username=roy&password=spring`.
May be this is not secure. what is the recommended way here?

```java
@Bean
	@Qualifier("myFullAcessDetails")
	protected OAuth2ProtectedResourceDetails fullAccessresourceDetails(
			String tokenUrl) {
		ResourceOwnerPasswordResourceDetails resource = new ResourceOwnerPasswordResourceDetails();
		resource.setAccessTokenUri(tokenUrl);
		resource.setClientId("clientapp");
		resource.setClientSecret("123456");
		resource.setGrantType("password");
		resource.setScope(DemoApplicationUtils.getScopesList("read", "write"));
		resource.setUsername("roy");
		resource.setPassword("spring");
		return resource;
	}
```

I am interested to see how I can use this sample as a controller that authenticates with authServer for a given user and the controller subsequently makes micro-services calls. 
 this [post](https://stackoverflow.com/questions/31525237/how-to-get-scope-associated-with-access-token-in-spring-oauth-while-building-mic) for more info.

Looking forward to more samples from you (may be microservices that authenticates with AuthServer ??). Thanks for the contributing these.

Thanks

**Comment by mariubog** [comment]
ad 1
This example is little misleading if you look at it and I am sorry about that.
Basically because Roy does not provide access to the resource that would be accessible only by the client without user authentication. I ll try to ask Roy to update and send him pull request.
Here is what I mean, I just wanted to show how to write template that will work with client only authentication from the point of view of the creator of template. 
If you look at the code you will see that I override in `ClientOnlyResourceOwnerPasswordResourceDetails` `isClientOnly` to return `true` instead of default `false` for `BaseOAuth2ProtectedResourceDetails` it is false because it requires identification of the User by default, by making 'clientOnly' return true it only requires identification of the Client without previous authentication of the User. 
It shows how to do it if there is resource on the Oauth server that allows access only with client authentication without (default for the template) user authentication.
But since there is no such a resource my `OAuth2ProtectedResourceDetails` implementation for this approach still provides username and password of the user besides the client credentials. Its a cheat and I ll try to fix it when I have little time.  Oauth server distinguishes between client and user and they are both completely different entities.

ad 2 Part of the response to this one is already in point 1, when to use them? basically client only is used when you access resource that is not reserved for any particular user  or before user is authenticated you just provide clientid and secret and you will receive token for your purpose. 

ad 3 Yes it is hard coded just to show you basics, in real life most of this stuff would be either provided by the user or read from some external store. I just made it simple and tried to make it visible how to create Oauth template, because few people have been having problems with it. If you want to provide your own credentials of course some of this stuff can not be created as hard coded beans but `OAuth2RestOperations` does allow you to access predefined resourceDetails `getDetails()` and then maybe cast it into `ResourceOwnerPasswordResourceDetails ` and provide your own credentials. It is really up to you how you design it.

Quote:
"something like this
http://localhost:8005/results-asynch?username=roy&password=spring."

`result-asynch` does not seem to work for me at the moment maybe is is due to updating and changes in new version, I do not know. I ll look at it when I have little time next couple of days.
Besides whole login process is having problem in this little example. I ll look at it in next couple of days.

Sorry for inconvenience.

**Comment by sridhar1982** [comment]
thanks for the detailed answer. I appreciate it.

It would be really useful to know how to allow resource access that requires only client authentication but not user authentication. Either you can make a Pull Request to Roy or clone the project here and make a commit that will be a good reference.

One more issue
when I try
`http://localhost:8005/authorized-results`
I get redirected to `http://localhost:8005/login` and it is `whiteLabel Error` page. I think you are aware of it.

In your free time, if you could give an example of bean where username and password could be dynamically passed (using `OAuthRestOperations` as you mentioned above).

would it be possible for you to show how to exchange refresh token for access token when access token expires? That will be very helpful.

Thank you very much

**Comment by mariubog** [comment]
@sridhar1982 
 sridhar1982 
OK sorry it took me so long but I just made necessary changes to fix the problem.
So I ll try to go over them to answer your questions.
First I have to state that it does not work anymore with Roy's example so you will have to use my fork for his app https://github.com/mariubog/spring-rest-service-oauth   instead of the original.
I ll try to send pull request when I am 100% done.

First Roy's example.
Major change that I done to Roy's example is  changing clients configuration. I created two different client where one is authenticated only with client credentials while other requires full user credentials
You can see it here:
https://github.com/mariubog/spring-rest-service-oauth/blob/master/src/main/java/hello/OAuth2ServerConfiguration.java
I also added new endpoint accessible only by the client
I posted curl commands in the comments to depict the behavior of the app with this configuration.
It is self explanatory I think.

Now to my example for oauth template.
Major changes needed to be done to `OauthClientConfig`
https://github.com/mariubog/oauth-client-sample/blob/master/src/main/java/oauth/client/demo/config/OauthClientConfig.java
As you can see I had to create two different `OAuth2ProtectedResourceDetails` one for `user` , `password` credentials authentication and other for `ClientCredentials`, You can notice that they both require different credentials to authenticate. User does not need secret and accordingly client does not need user information.
If you have tow approaches you also need two different `AccessTokenProvider ` implementations.
But you can see all of that in the code.
Now to go over each approach that is available as controller endpoint.
https://github.com/mariubog/oauth-client-sample/blob/master/src/main/java/oauth/client/demo/MyRestController.java
I ll start from the bottom
`/authorized-results` is the endpoint that is protected by `WebSecurityConfig`
https://github.com/mariubog/oauth-client-sample/blob/master/src/main/java/oauth/client/demo/config/WebSecurityConfig.java
so it only allows access if user is authenticated, it is important because using `oauthTemplate` `AccessTokenProviderChain` always checks if user is authenticated and if this is not `clientOnly` resource we will get `InsufficientAuthenticationException`.
You asked me how to provide credentials to template instead of hard coding them, I showed in comments how to do that, but how you obtain username and password is up to you, adding form to get these information is beyond the scope of this example and you cant get them from the user object because password is cleared after successful authentication so you have to write method to get them from the user again and pass them to controller.

Next one is `/results' and it is the endpoint that connects to client only resource. All configuration for it is done in `OauthClientConfig` and it is trying to reach endpoint `/credential_greeting` opposite to previous one with user details and reaching `/greeting` endpoint.

Other two `/results-nonauthorized` and `/results-asynch` are only to show some behavior of template, I don't think you would ever use them in real live, result asynch shows that step of checking for authenticated user is not present when we are operating in asynch thread but oauth server still requires the same authentication it is only internals of token obtaining by template.
And the second one does similar since authentication is checked in `AccessTokenProviderChain`

```	
if (auth instanceof AnonymousAuthenticationToken) {
			if (!resource.isClientOnly()) {
				throw new InsufficientAuthenticationException(
						"Authentication is required to obtain an access token (anonymous not allowed)");
			}
		}
```  
but we supply our own `AccessTokenProvider` so it is not the case.

**Comment by sridhar1982** [comment]
Hey thanks for working on this. very helpful. If I want both Client and User to be authenticated,
for this URI "/client_user_greeting", can I do the following:

                                    
                                  http
 				         .authorizeRequests()
 					 .antMatchers("/users").hasRole("ADMIN")
					.antMatchers("/client_user_greeting").authenticated();
					.antMatchers("/greeting").hasRole("USER")
					.antMatchers("/client_greeting").access("#oauth2.isClient()");

Another question:

you mentioned "/greeting" require only user but NOT client authentication.
However, you have configured with client credentials

```java

@Bean
	@Qualifier("myFullAcessDetails")
	public OAuth2ProtectedResourceDetails fullAccessresourceDetails(String tokenUrl) {
		ResourceOwnerPasswordResourceDetails resource = new ResourceOwnerPasswordResourceDetails();
		resource.setAccessTokenUri(tokenUrl);
		resource.setClientId("user_member");
		resource.setGrantType("password");
		resource.setScope(DemoApplicationUtils.getScopesList("read", "write"));
		resource.setUsername("roy");
		resource.setPassword("spring");
		return resource;
	}

```

**Comment by mariubog** [comment]
I would rather do sthg like this
```
 .antMatchers("/client_user_greeting").access("(#oauth2.isClient() && #oauth2.hasRole('CLIENT')) or (#oauth2.isUser() && #oauth2.hasRole('USER'))");

```

"you mentioned "/greeting" require only user but NOT client authentication.
However, you have configured with client credentials"
nope I provide only user credentials, notice that `secret` (123456 for client) is not provided in this configuration for user, and clientId is neccesary to establish authentication

**Comment by sridhar1982** [comment]
your matcher above will let either client Or USER to pass through. I want both Client and USER authenticated (like I develop a client that uses FB API. FB needs both client and user credentials to grant access token to client app).

For the second part,
```
resource.setClientId("user_member");
        resource.setGrantType("password");
```
so is this dummy and serves no purpose? needed only for Spring-OAuth-support?

**Comment by mariubog** [comment]
I am not sure what you mean by dummy, it has to match the grant types specified for `user_member` in Oauth clients configurations

```
.withClient("user_member")
						.authorizedGrantTypes("password", "refresh_token" )
						.authorities("USER")
						.scopes("read", "write")
						.resourceIds(RESOURCE_ID)
```
If you don't provide grant type in resource, authentication will fail due to wrong grant type.
If you develop for FB API which I am not familiar with I would suggest checking spring social.
In my approach both client and user are authenticated, otherwise they would not be granted role. they both are authenticated according to the specifics, client needs clientId and secret, user needs clentId, username and password to be authenticated.

**Comment by sridhar1982** [comment]
I am getting it now.

you suggested something like below:

```
.antMatchers("/client_user_greeting").access("(#oauth2.isClient() && #oauth2.hasRole('CLIENT')) or (#oauth2.isUser() && #oauth2.hasRole('USER'))");
```
-- what is implied here? you are asking for either client OR User Role, but not both. 

Another question on same thing
how does `#oauth2.isClient()` and `#oauth2.hasRole('CLIENT')` are different?

Last question. In the `MyRestController.java` , you mentioned in the comment:
"User is being redirected to login page for required authorization This
	 * uri REQUIRES authentication on client side "

But actually I dont see redirection happening to login page? is anything missing here?

**Comment by mariubog** [comment]
You mean that If you go to `/authorized-results` it does not redirect you to login form?

**Comment by sridhar1982** [comment]
yes, that is correct. it is not redirecting to login form

can you also answer this part:

```.antMatchers("/client_user_greeting").access("(#oauth2.isClient() && #oauth2.hasRole('CLIENT')) or (#oauth2.isUser() && #oauth2.hasRole('USER'))");```

-- what is implied here? you are asking for either client OR User Role, but not both.

**Comment by mariubog** [comment]
`http://localhost:8005/authorized-results` you have to be doing something wrong because when I select that link and am not previously authorized, it redirects you to `login` page, are you sure you downloaded this sample after update on July 29th , please download it again and check.

`.antMatchers("/client_user_greeting").access("(#oauth2.isClient() && #oauth2.hasRole('CLIENT')) or (#oauth2.isUser() && #oauth2.hasRole('USER'))");`

you can set your authorization restrictions whichever way you want , just mix and match I wrote `isClient()` and `oauth2.hasRole('CLIENT')` because you can have clients that are `clients` but have assigned different role so can user does not have to have role `USER` it may for example be `USER_X` , `USER_Y` etc., it is  up to you how you set it  is just a simple suggestion for authorization matchers

**Comment by sridhar1982** [comment]
Tests are failing in your fork of `RoyClarkson` 
https://github.com/mariubog/spring-rest-service-oauth

were you able to run `mvn clean package` successfully?

```
Failed tests: 
  GreetingControllerTest.usersEndpointAccessDenied:152->getAccessToken:95 Status expected:<200> but was:<401>
  GreetingControllerTest.usersEndpointAuthorized:142->getAccessToken:95 Status expected:<200> but was:<401>
  GreetingControllerTest.greetingAuthorized:111->getAccessToken:95 Status expected:<200> but was:<401>
```

**Comment by mariubog** [comment]
You have problem with packaging for some reason  make sure that import.sql  is executed properly,
are you using eclipse?
Where is your import.sql  located after you unpackege everything?

**Comment by sridhar1982** [comment]
I am using eclipse. I pulled your git fork and execute mvn clean package in the repo. But the original repo of Roy, build was successful.

Did you make package on the fork?

**Comment by mariubog** [comment]
well I think eclipse messes something up, where is your import.sql located?

**Comment by mariubog** [comment]
https://github.com/mariubog/spring-rest-service-oauth/archive/master.zip  this is the link to zip
unpack it and then use maven

**Comment by sridhar1982** [comment]
I did not run mvn package from eclipse.  I ran from commandLine. I will try using the zip. import.sql is in src/main/resources. I don't think it is problem with import.sql

**Comment by mariubog** [comment]
How do you know it is not the problem with import.sql, do you see it executed?

**Comment by sridhar1982** [comment]
I unpacked the zip you provided and executed maven. still I get same error. 

I can see from log that import.sql is executed

```
12:54:05.747 [main] INFO  o.h.tool.hbm2ddl.SchemaExport - HHH000227: Running hbm2ddl schema export
12:54:05.748 [main] DEBUG org.hibernate.SQL - alter table user_role drop constraint FK_it77eq964jhfqtu54081ebtio
12:54:05.749 [main] ERROR o.h.tool.hbm2ddl.SchemaExport - HHH000389: Unsuccessful: alter table user_role drop constraint FK_it77eq964jhfqtu54081ebtio
12:54:05.749 [main] ERROR o.h.tool.hbm2ddl.SchemaExport - user lacks privilege or object not found: PUBLIC.USER_ROLE
12:54:05.749 [main] DEBUG org.hibernate.SQL - alter table user_role drop constraint FK_apcc8lxk2xnug8377fatvbn04
12:54:05.749 [main] ERROR o.h.tool.hbm2ddl.SchemaExport - HHH000389: Unsuccessful: alter table user_role drop constraint FK_apcc8lxk2xnug8377fatvbn04
12:54:05.749 [main] ERROR o.h.tool.hbm2ddl.SchemaExport - user lacks privilege or object not found: PUBLIC.USER_ROLE
12:54:05.749 [main] DEBUG org.hibernate.SQL - drop table role if exists
12:54:05.749 [main] DEBUG org.hibernate.SQL - drop table user if exists
12:54:05.749 [main] DEBUG org.hibernate.SQL - drop table user_role if exists
12:54:05.749 [main] DEBUG org.hibernate.SQL - create table role (id integer generated by default as identity (start with 1), name varchar(255) not null, primary key (id))
12:54:05.750 [main] DEBUG org.hibernate.SQL - create table user (id integer generated by default as identity (start with 1), login varchar(255) not null, name varchar(255) not null, password varchar(255) not null, primary key (id))
12:54:05.751 [main] DEBUG org.hibernate.SQL - create table user_role (user_id integer not null, role_id integer not null, primary key (user_id, role_id))
12:54:05.751 [main] DEBUG org.hibernate.SQL - alter table user add constraint UK_ew1hvam8uwaknuaellwhqchhb  unique (login)
12:54:05.752 [main] DEBUG org.hibernate.SQL - alter table user_role add constraint FK_it77eq964jhfqtu54081ebtio foreign key (role_id) references role
12:54:05.753 [main] DEBUG org.hibernate.SQL - alter table user_role add constraint FK_apcc8lxk2xnug8377fatvbn04 foreign key (user_id) references user
12:54:05.756 [main] INFO  o.h.tool.hbm2ddl.SchemaExport - HHH000230: Schema export complete
```

**Comment by mariubog** [comment]
I don't It is just the info that schema in DB is created. It says nothing about inserting values from import.sql. The above is executed based on how you define your entities. It is basic part of springboot.

**Comment by sridhar1982** [comment]
my import.sql is in src/main/resource. I did NOT change anything. I pulled the git repo and even tried the zip you provided above. However, the build was successful using Roy repo.

**Comment by mariubog** [comment]
that is strange because I am having no problem, I am sure it is import.sql that is not executed in your case, I am going to have to look for the problem.

**Comment by sridhar1982** [comment]
Thanks for helping here. I can send the entire log if that will help you!

**Comment by mariubog** [comment]
Sorry my bad, I forgot to change the updated tests, I ll post it in 10 minutes.

**Comment by mariubog** [comment]
Ok tests should work now, try it when you got the chance , sorry for the problems.

**Comment by mariubog** [comment]
@sridhar1982 I am closing this issue since I think for now all the problems have been resolved I f you have any more issues that should be dealt with here feel free to reopen it.
